[config]
version_check = false

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/bg-colors.conf'
post_hook = 'pkill -SIGUSR1 kitty'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.qt6-kde]
input_path = '~/.config/matugen/templates/matugen.colors'
output_path = '~/.local/share/color-schemes/matugen.colors'

[templates.yazi]
input_path = '~/.config/matugen/templates/yazi-colors.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.pywalfox]
input_path = '~/.config/matugen/templates/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

[templates.vesktop]
input_path = '~/.config/matugen/templates/midnight-discord.css'
output_path = '~/.config/vesktop/themes/midnight-discord.css'

[templates.folder]
input_path = '~/.config/matugen/templates/folder-color.txt'
output_path = '~/.config/matugen/papirus-folders/folder-color.txt'

[templates.waybar]
input_path = '~/.config/matugen/templates/waybar.css'
output_path = '~/.config/waybar/waybar.css'

[templates.swaync]
input_path = '~/.config/matugen/templates/swaync.css'
output_path = '~/.config/swaync/swaync.css'