[colors.primary]
background = "#0f0a17"
foreground = "#c3c1c5"

[colors.cursor]
text = "#0f0a17"
cursor = "#c3c1c5"

[colors.vi_mode_cursor]
text = "#0f0a17"
cursor = "#c3c1c5"

[colors.search.matches]
foreground = "#0f0a17"
background = "#c3c1c5"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#62596d"
background = "#c3c1c5"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0f0a17"
red = "#BB554B"
green = "#E2A055"
yellow = "#D3B46B"
blue = "#2B4C9B"
magenta = "#2F4E9A"
cyan = "#566398"
white = "#c3c1c5"

[colors.bright]
black = "#62596d"
red = "#BB554B"
green = "#E2A055"
yellow = "#D3B46B"
blue = "#2B4C9B"
magenta = "#2F4E9A"
cyan = "#566398"
white = "#c3c1c5"

[colors.dim]
black = "#c3c1c5"
red = "#BB554B"
green = "#2F4E9A"
yellow = "#D3B46B"
blue = "#2B4C9B"
magenta = "#E2A055"
cyan = "#566398"
white = "#62596d"

