[colors]
background = '#0f0a178e'
black = '#0f0a17'
blue = '#BB554B'
cursor = '#c3c1c5'
cyan = '#E2A055'
foreground = '#c3c1c5'
green = '#D3B46B'
magenta = '#2B4C9B'
red = '#2F4E9A'
tabs = '#c3c1c5'
tabs-active = '#566398'
white = '#c3c1c5'
yellow = '#c3c1c5'
dim-black = '#0f0a178e'
dim-blue = '#BB554B8e'
dim-cyan = '#E2A0558e'
dim-foreground = '#c3c1c58e'
dim-green = '#D3B46B8e'
dim-magenta = '#2B4C9B8e'
dim-red = '#2F4E9A8e'
dim-white = '#5663988e'
dim-yellow = '#c3c1c58e'
light-black = '#BB554B'
light-blue = '#E2A055'
light-cyan = '#D3B46B'
light-foreground = '#2B4C9B'
light-green = '#2F4E9A'
light-magenta = '#566398'
light-red = '#c3c1c5'
light-white = '#BB554B'
light-yellow = '#E2A055'
